language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
    - AZURE_ACCOUNT_NAME=sakamatest
    - AZURE_CONTAINER=blobcontainers
    - AZURE_CONTAINER_IMPORT_DIRECTORY=unittests_import
    - secure: "kcQtK4pbq9ldVFOQXRiPd+ieVokGfPWfc45bZu9iAags68sFhUHxs0WrT4Io2RZvYSIQ7t5OHYwF8TUqgecaMPmoQmNkUHozgVoJ1oBu9BwA2ceh+u7/pkWPJ0VsAPW2+LE2uMC67MrvayeIxV3wuCCDdBHd2F64Ja8AE7p8Re8vrrDvD8BVF6+OqHma0S8i7PCZE+4rYeJpITbAAQ8PqMa8P/6Wkbp0LSJCAiDhwc/89wGn8wlZkju/aUGz0tG89Yq3Iw+xonhsPhLi910rg31vIMEH/K14I/uiUOaxavvxzc37fHAJgMzhQnRN67qhVuX5eocMosDAVAsXByURYAGZ4/f4sLqsghGkh4f+b96AchiGvM62hbwPyn1BMBl6fOezap5LOMAKjSZBReHNN2Hau+7YXDhqv2aVxVLWwXHDJQ8KhgMn10EZ+W3U5KuNLaGrfcrPfWIDxcR3rU81SXkzAyoHri895xlXq+CxsWOlYsXpWwpX14hNIJzcqtq9KQt+U34Xyw/whBsrSZbCitTZvPiTC9pFvCXBddpz07KqaUeUYwneGbVdCjpq42OO5bybSOAHEI8U7Ay7ldEFs0mRq8HzEOrhwZIdAgODsujQwV1jFgz6yKNwKTE6jx8UOqUQKalQjiAt0he4Pz8BjH+uxmRRvALNjF0ZWOMl5UU="

script:
  - ./gradlew gem
  - ./gradlew --info check jacocoTestReport

